# Generated by Django 6.0 on 2025-12-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_car_image_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('armenia', 'ՀՀ-ում'), ('transit', 'Ճանապարհին'), ('auction', 'Աճուրդում')], default='auction', max_length=20, verbose_name='Կարգավիճակ'),
        ),
    ]
